services:
  php-client:
    build:
      context: ./client
    depends_on:
      - database-client
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}

    volumes:
      - ./client:/var/www/client

  php-restaurant:
    build:
      context: ./restaurant
    depends_on:
      - database-restaurant
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}

    volumes:
      - ./restaurant:/var/www/restaurant

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./client:/var/www/client
      - ./restaurant:/var/www/restaurant
    ports:
      - "80:80"

  database-client:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=client
      - MYSQL_USER=client
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  database-restaurant:
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_DATABASE=restaurant
      - MYSQL_USER=restaurant
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
